# a = input("Enter your name : ")
# print("My name is ",a)
#  #next
# x = input("Enter first number :")
# y = input("Enter second number :")
# print( "The sum will be :",int(x)+int(y))
# b = "vaibhav"
# print(b[ : ])
# print(b[0:])
# print(b[:4])
# print(b[:6])
# print(b[3:6])
# print(b[-3:-1])
# print(b[:])
# print(b[-4:])
# print(b[:-2])
c = "sammy shank!"
print(c[0:12])
print(c[0:12:1])
print(c[0:12:2])
print(c[::-1])
print(c[::-2])
print(c[6:12:2])  
print(c[0:12][::-1])