#relational operators. ( = , == ,!= , > , <, <= ,>= )
a = input("Enter the number: ")
b = input("Enter the number : ")
print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)